language: python
python:
  - "3.13"

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings
    - USE_SQLITE_FOR_TESTS=1

branches:
  only:
    - main
    - test

install:
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls
  - pip install awscli

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coveralls

before_deploy:
  - echo "Checking AWS credentials..."
  - aws s3 ls s3://elasticbeanstalk-us-east-1-423158040784 --region us-east-1

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "swe1-app"
  env: "swe-sj4771"
  bucket: "elasticbeanstalk-us-east-1-423158040784"
  on:
    branch: main
  skip_cleanup: true